### PR TITLE
bug fix issue 74

### LINKED ISSUE #74: Edit resets attendance

### PR DESCRIPTION
**Pull request by limzishen**
Fixes #74

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -101,9 +102,10 @@ private static Person createEditedPerson(Person personToEdit, EditPersonDescript
         StudentId updatedStudentId = editPersonDescriptor.getStudentId().orElse(personToEdit.getStudentId());
         TutorialGroup updatedTutorialGroup = editPersonDescriptor.getTutorialGroup()
                 .orElse(personToEdit.getTutorialGroup());
+        Attendance attendance = personToEdit.getAttendance();
 
         return new Person(updatedName, updatedPhone, updatedEmail, updatedTeleHandle, updatedStudentId,
-                updatedTutorialGroup);
+                updatedTutorialGroup, attendance);
```
Comment (danielyap4103) [inline src/main/java/seedu/address/logic/commands/EditCommand.java]: Good bug fix!
